language: java
jdk:
 - oraclejdk8

# safelist
branches:
  only:
  - test
  - master

services:
  - mysql

env:
  - global:
    # STAGING_USER
    - secure: "JomuXbxf4i7MTAaatUTmrzkfGU63rbOuNSQVQ7qe1tWWrwpsZfMGiAGEPz5iDPh95QtO3Wl3XiM52o+JfBx5IAqlGCvJKs/mnZpD30AgLOCUFoNxctAjl6nwr6D3Z7pdrW50M5pdLJ1rib+o70IOXS+OJCJjCScdUCM15XVD/Z/qkQlYVzqkyEzKPEKD5GGsUL6UI9edWxkX7a9+g/x2alxexZM3H+x8s7+sz684n+WgQAMhGv12Ks66jyhwXWkShRlMYF5ghlYZez33YDQdz5v8iHW25M9n4Fwuraq+yGYPVL3jGAz1K0gh5194T0NAew+1XbS/UQJmJ7hNodeYyE7O/Jdgm/8OcKu5HOrxoJxldiHvCNCjRtJI0FbjsTleLxRWbulrsZGhDX1UefBhouePyCQNm0a0fAgmdBohsbCcLunT35qosmofDuaZ06F1FSfNTHEhRVLnCTwrCTo8X9KNraXo8Tha5bP1RSRi7J9PYa6xxCAlLVnZgVjimi2xxumxNfZag0QlVcfG2cl7qa2TBU3dImJB9xfkbxWDWsY0OfejoCq4AUCTuhAQK7/wXAK7DV6Nct+zuoSv+eI9Tdpp/8Zzwy4/D/0nBmbH9qVg4uuWCgfFDE0O6mHJdTUxAB4kK1ZzBSU8RhywhZdAAi7HkdHmYtL2jRq6pWBJ4Sk="
    # STAGING_PW
    - secure: "L07gCWQTryn4pQG4cvjybu1Zboyiwa/UV+xw//OrJEv9kLMn052ob7Lxic69/o0yvk6+ABIII8CvN23PFTnyhTqGJzOb1GisleuYOfYM0GBeZ7lLjXMV0uXVaw2zeWjlSJwJpPsPEtL4F+5JKUyMmOBnqvT9YhweDd8DCWSogg+vtkzGnNZAqb5a8Ou28VNShYIR05k6EccqEzVrEbGMdX/r6UtoR4tNtwyDj5z4pBibKTNVEAdTuNtYxlXN7cEp6qYCheZ2qLqXP45e2Crd9oNMqDSPY7O5+vbI6jJUDxgIJ9gQ5POZSoyZASoNoaTTqz3EfNuBK7LUlXzPog9uVgbbw3RQaxlBAJKR9o5CJrLpBntpvGZgCmEF/FIIP05GE15B96G8jXMgPleB81ojCa22t0/LRk15AUpBKF11qS0N3joYSWQLm4hucdKiGQXRgizELjb3T8uUtCjdKRxpLBol7aTI6A9GVNUcvWXbKbQ5hwssrqR6dq1OTqQgbPIOl43fbbVCSdR9+hG0H1IW8lBTq1EvtEEqCwTXKUF8quO1nD8BtXTn20/F/uyrh2bZ+AhGCZNjjVW/Jbk7cZ3SipyvIeFTjV8J/h646uTHJ6OVBVCVOdwbFm5PNivSJdiiVYttAs2oTXPtTToFaplelCtFLOPvc6t105UvmtZ4yQo="
    # PROD_USER
    - secure: "nXX84K/urzpToLPmi0WT5WPJgjD481yHbceDoku4/W5F/ryCcuAYWj1foa/gGsZqtSXcrdYz+hderGSisWin+K9Vw97nH+cKWhVXq0Lzy5wm2Ok074qJMmldYkkOiZtoZqT9r8eKnTpw7FFq6bn3YFHMILwb7U2XH+JpSYEo/qi8fexgulthoar77KAX0siXGw+zc6p0aL9nmcINiHusFWK5tQn0V6NgQkyXlRB9JaMPhOsoqtRmY8G9CqPU+9nzRFbIlrxviF8YCkQRPQgj+rpJ8fpCcHiBNrBwTemWtTfBWDEgfZGqOieRjIBaY6tju4c9Q/foxl+Uva2oe6mhaPFtyzjmvtRUfw0BRk54srFH+Z1ZvSIX3P524SmhLVMnXZCtNJOiceNiZjOP7YaLO3ECds7DiahNpOMoHnf/zRXAfgreK3SCRwZHZTe3ug5G3uyl05mFVkfBVbyEYSuW0qLnpYxJYqFWTSMNIIp/Hdft+hRKDCOCNyW/mZLo0NpYwH2d3/02jSjRfbxR5+2pzEzC5358NEr8SR0VksAt4xkdtgZuCLPTbRdazn8LYOTL+FFRDHFol2XtA6mBab2fwYjOre8VArnWrjflYD1WHp546iVpGj8M5frT+NFJTsDVkFE5zEqE1iac67y6KBUWa4p+I/YHF3OO5gsELb6AMuQ="
    # PROD_PW
    - secure: "IuQXFQzJrtfdw2GbRSabU9QJIk9uYH0djlZ1gPB4wYDBnZiG6nQbVowlST95grk0DW9LBmD5yKbAczr+LYRolTuMnyjJXFcet24+1ywlLxWuQzTCiazZzQV+wuX4x3wdqa9Q+XnM8sZ3m1ZOpFXhLgNPR3U8c4+vF0BRN6HN/kEJH/yqmd1WBD0P1b3s6km2L0IDkX+hsos7EIAuQoMho6iYW6/y7xZyHaoUn37do9b3F0knOitUxL0Y1TfQdldSqkKOiEv2LdSspmpJXJ/KRniY/4NafATH9LbGXJPVj9RlS9P9tIQ6U4nkFxsbJ2bbaozxU2yjSSOovnho/Uoy7QMcTnVrpCr5ZwYYBLQBnc4jNMUV+MgxLGZ37UyyEoMLO+dn79pLywdSRGT9H03KdAWHfxnxDE9BrjjfLV4am+WrN5mf+PIIcSNh58GiQwYAg/i/FKCAykttdzXs0Ct+lon5OiPpyJGlHxL6AvdQk7oKQnGV4ng4PNoOITlqNsHzTiZX34vHvJ5gT5GeUQ57Tx1yPfzlUEyBsoWQb5AUSvLVRuYS4ilaMcMIe3rj3BopGlBosxh7LRgs71Is+6yR7o778RIMu6uA2PuHjppIcRznhKDujybeIVwKvDTWqzOdKmB7Gi5WAGqmoCyR/Wptkw22R+OFpbpuxzWAfklK/O8="
    - STAGING_URL=jdbc:mysql://127.0.0.1:3306
    - PROD_URL=jdbc:mysql://127.0.0.1:3306
    - SCHEMAS=public
    
install:
  - wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.0.7/flyway-commandline-5.0.7.tar.gz && tar -xvzf flyway-commandline-5.0.7.tar.gz && cd flyway-5.0.7

script:
 - |
    if [ $TRAVIS_BRANCH == "test" ]; then
      ./flyway -url=$STAGING_URL -user=$STAGING_USER -password=$STAGING_PW -locations=filesystem:../analyst/dwh/incremental_migrations -schemas=$SCHEMAS migrate
    elif [ $TRAVIS_BRANCH == "master" ]; then
      ./flyway -url=$PROD_URL -user=$PROD_USER -password=$PROD_PW -locations=filesystem:../analyst/dwh/incremental_migrations -schemas=$SCHEMAS migrate
    fi

after_failure:
 - |
    if [ $TRAVIS_BRANCH == "test" ]; then
      ./flyway -url=$STAGING_URL -user=$STAGING_USER -password=$STAGING_PW -locations=filesystem:../analyst/dwh/incremental_migrations -schemas=$SCHEMAS repair
    elif [ $TRAVIS_BRANCH == "master" ]; then
      ./flyway -url=$PROD_URL -user=$PROD_USER -password=$PROD_PW -locations=filesystem:../analyst/dwh/incremental_migrations -schemas=$SCHEMAS repair
    fi

