CREATE TABLE public.`test_table` (
  `purchase_transaction_id` int(11) unsigned NOT NULL,
  `extension_num` smallint(8) unsigned NOT NULL DEFAULT '0',
  `purchase_id` int(8) unsigned NOT NULL,
  `user_id` int(8) unsigned NOT NULL,
  `sku_id` int(8) unsigned NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `start_month` mediumint(6) unsigned NOT NULL DEFAULT '0',
  `extension_month` mediumint(6) unsigned NOT NULL DEFAULT '0',
  `extension_date_sk` int(8) unsigned NOT NULL DEFAULT '0',
  `date_sk` int(8) unsigned NOT NULL DEFAULT '0',
  `currency` varchar(3) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `price_net` mediumint(5) NOT NULL,
  `vat` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `l2` varchar(3) COLLATE utf8_unicode_ci NOT NULL DEFAULT '---',
  `lead_date_sk` int(8) unsigned NOT NULL DEFAULT '0',
  `lead_channel_sk` int(5) unsigned NOT NULL,
  `key_country_code` varchar(3) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'ROW',
  `created_at` datetime NOT NULL,
  `product_key_code` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `subscription_mode` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sales_group` varchar(50) COLLATE utf8_unicode_ci DEFAULT 'normal',
  `payment_method` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `recurring_months` tinyint(2) unsigned DEFAULT NULL,
  `payment_provider_type` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'na',
  `payment_provider` varchar(20) CHARACTER SET utf8 NOT NULL DEFAULT '(na)',
  PRIMARY KEY (`purchase_transaction_id`),
  UNIQUE KEY `idx_transaction_id` (`purchase_transaction_id`),
  UNIQUE KEY `idx_purchase_id_transaction_id` (`purchase_id`,`purchase_transaction_id`),
  KEY `extension_num` (`extension_num`,`product_key_code`,`subscription_mode`,`sales_group`,`start_month`),
  KEY `idx_purchase_then_date` (`purchase_id`,`date_sk`),
  KEY `date_sk` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
;
